### ISSUE TITLE
Добавить логотип университета в sidebar

### ISSUE THREAD

**Issue by KMax** [ailabitmo/ailabitmo.github.io#5]
Наподобии sidebar в правом верхнем углу http://aksw.org/About.html

**Comment by KMax** [comment]
Эээ...ты закоммитил изменения?

**Comment by ghost** [comment]
Сорри, забыл запушить сначала :)

**Comment by KMax** [comment]
Бывает :)

Может быть лучше поднять блок с логотипом, чтобы он был сразу после блока со сменой языка? И уменьшить примерно на 20% процентов в размере. Что думаешь?

**Comment by ghost** [comment]
Я думал об этом, но решил что твиттер-лента концептуально важнее, хотя мб я ошибаюсь тут. В принципе, наверное, ты прав, т.к. мы лаборатория при ИТМО, это должно быть сразу понятно.

Насчет логотипа. Вот уменьшил на 20% примерно, но не могу понять, стало ли лучше, т.к. засыпаю, поэтому отдаю на твой суд. Если понравится, то замени лого в репозитории вот этой картикой: https://dl.dropboxusercontent.com/u/9408339/itmo.png (мне лень было в стилях это настраивать).

![screenshot 2015-03-11 22 54 53](https://cloud.githubusercontent.com/assets/1007225/6606681/18bdca00-c842-11e4-82c7-6524df5b9c07.png)
